// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MIS_Prog_App.Models
{
    public partial class Registration
    {
        public int RegId { get; set; }
        public string First { get; set; }
        public string Last { get; set; }
        public string Em { get; set; }
        public int Id { get; set; }

        public virtual Event IdNavigation { get; set; }

        public Registration(string first, string last, string em)
        {
            
            First = first;
            Last = last;
            Em = em;
           
        }
    }
}